export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const USER_PROFILE = "USER_PROFILE";
export const USER_ERROR = "USER_ERROR";
export const GET_USER = "GET_USER";
export const USERS_LOADED = "USERS_LOADED";

export const SET_SIZE_SUCCESS = "SET_SIZE_SUCCESS";
export const SET_SIZE_FAIL = "SET_SIZE_FAIL";
export const GRID_CREATED = "GRID_CREATED";
export const BACKGROUND_FILLED = "BACKGROUND_FILLED";

export const SET_DEFAULT = "SET_DEFAULT";
export const DISCARD_GRID = "DISCARD_GRID";
export const PENCOLOR_CHANGED = "PENCOLOR_CHANGED";

export const EDITOR_MODE = "EDITOR_MODE";
export const EXPORT_IMAGE = "EXPORT_IMAGE";
export const TOOL_CHANGED = "TOOL_CHANGED";
export const USE_PIPETTE = "USE_PIPETTE";

export const SAVE_IMAGE = "SAVE_IMAGE";
export const GET_IMAGE = "GET_IMAGE";
export const IMAGE_LOADING = "IMAGE_LOADING";
export const IMAGE_DELETED = "IMAGE_DELETED";
export const IMAGE_UPDATED = "IMAGE_UPDATED";
export const IMAGE_ERROR = "IMAGE_ERROR";

export const GALLERY_LOADING = "GALLERY_LOADING";
export const GALLERY_LOADED = "GALLERY_LOADED";
export const GALLERY_ERROR = "GALLERY_ERROR";

export const POST_CREATED = "POST_CREATED";
export const POST_ERROR = "POST_ERROR";
export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const POSTS_LOADING = "POSTS_LOADING";
export const GET_POST = "GET_POST";
export const LIKED = "LIKED";
export const POST_UPDATED = "POST_UPDATED";
export const POST_DELETED = "POST_DELETED";
export const POST_SAVED = "POST_SAVED";

export const PROFILE_PICTURE_CHANGED = "PROFILE_PICTURE_CHANGED";
export const BACKGROUND_PICTURE_CHANGED = "BACKGROUND_PICTURE_CHANGED";
export const USER_UPDATED = "USER_UPDATED";
export const USER_UPDATE_ERROR = "USER_UPDATE_ERROR";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";

export const GRID_CLEARED = "GRID_CLEARED";

export const CATEGORIES_LOADING = "CATEGORIES_LOADING";
export const CATEGORIES_LOADED = "CATEGORIES_LOADED";
export const CATEGORY_ERROR = "CATEGORY_ERROR";
export const CATEGORY_SAVED = "CATEGORY_SAVED";
export const CATEGORY_UPDATED = "CATEGORY_UPDATED";
export const CATEGORY_LOADED = "CATEGORY_LOADED";
export const CATEGORY_LOADING = "CATEGORY_LOADING";
export const CATEGORY_DELETED = "CATEGORY_DELETED";

export const COMMENT_ADDED = "COMMENT_ADDED";
export const COMMENT_ERROR = "COMMENT_ERROR";
export const COMMENTS_LOADING = "COMMENTS_LOADING";
export const COMMENTS_LOADED = "COMMENTS_LOADED";
export const COMMENT_DELETED = "COMMENT_DELETED"; 
